- name: Install and start firewalld service
  hosts: firewall
  become: true
  tasks:
    - name: Install firewalld
      yum:
        update_cache: yes
        name: firewalld
        state: present

    - name: Enable and start firewalld service
      service:
        name: firewalld
        state: restarted
        enabled: true
