- name: Install and start firewalld service
  hosts: jumper
  become: true
  tasks:
    - name: Install firewalld
      apt:
        update_cache: yes
        name: firewalld
        state: present

    - name: Install python3-firewall
      apt:
        update_cache: yes
        name: python3-firewall
        state: present

    - name: Enable and start firewalld service
      service:
        name: firewalld
        state: restarted
        enabled: true

    - name: Stop and disable ufw
      service:
        name: ufw
        state: stopped
        enabled: false
