- name: Configure firewalld
  hosts: firewall
  become: true
  tasks:
    - name: Create zone wso
      firewalld:
        zone: wso
        state: present
        permanent: true
      notify: Reload firewalld

    - name: Add interfaces eth1 and eth2 to wso zone
      shell: |
        firewall-cmd --permanent --zone=wso --add-interface=eth1
        firewall-cmd --permanent --zone=wso --add-interface=eth2
      notify: Reload firewalld

    - name: Add  masquerade to wso zone
      firewalld:
        masquerade: true
        state: enabled
        permanent: true
        zone: wso
      notify: Reload firewalld  

    - name: Add  masquerade to public zone
      firewalld:
        masquerade: true
        state: enabled
        permanent: true
        zone: public
      notify: Reload firewalld 

    - name: Add ftp services to wso zone
      firewalld:
        zone: wso
        service: ftp
        state: enabled
        permanent: true
      notify: Reload firewalld   

    - name: Add http services to wso zone
      firewalld:
        zone: wso
        service: http
        state: enabled
        permanent: true
      notify: Reload firewalld   

    - name: Add port to public zone
      firewalld:
        zone: public
        port: 8080/tcp
        state: enabled
        permanent: true
      notify: Reload firewalld  

    - name: Add port forward to public zone
      firewalld:
        zone: public
        port_forward:
          - port: 8080
            proto: tcp
            toaddr: 192.168.1.10
            toport: 80
        state: enabled
        permanent: true
      notify: Reload firewalld  

    - name: Drop all not handled in zone public
      firewalld:
        zone: public
        state: enabled
        target: DROP
        permanent: true
      notify: Reload firewalld  

  handlers:
    - name: Reload firewalld
      systemd:
        name: firewalld
        state: restarted