- name: Configure firewalld
  hosts: jumper
  become: true
  tasks:
    - name: Create internal zone
      firewalld:
        zone: internal
        state: present
        permanent: true
      notify: Reload firewalld

    - name: Add internal subnet to internal zone
      firewalld:
        zone: internal
        interface: eth2
        state: enabled
        permanent: true
      notify: Reload firewalld

    - name: Create webapp zone
      firewalld:
        zone: webapp
        state: present
        permanent: true
      notify: Reload firewalld

    - name: Add webapp subnet to webapp zone
      firewalld:
        zone: webapp
        interface: eth1
        state: enabled
        permanent: true
      notify: Reload firewalld

    - name: Allow webapp to access FTP on internal
      firewalld:
        zone: internal
        service: ftp
        state: enabled
        permanent: true
      notify: Reload firewalld

    - name: Allow webapp to access FTP on internal
      firewalld:
        zone: webapp
        service: ftp
        state: enabled
        permanent: true
      notify: Reload firewalld

    - name: Add firewalld rule to allow SSH traffic
      firewalld:
        service: ssh
        permanent: true
        state: enabled
        immediate: true
      notify: Reload firewalld

    # - name: Add firewalld rule to block all other traffic
    #   firewalld:
    #     zone: drop
    #     permanent: true
    #     state: enabled
    #     immediate: true
    #   notify: Reload firewalld

  handlers:
    - name: Reload firewalld
      systemd:
        name: firewalld
        state: restarted